[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

#[[plugins]]
#repo = ''
